"""
Django settings for avt project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vt$23d6j$h82=z#%9xdc9wacd7c2%9nr0ch&8ohpuu2-@h^_fh'
APPEND_SLASH = False
CSRF_TRUSTED_ORIGINS = [
    'https://astcab.com',
    'https://www.astcab.com'  # Add this if the site can be accessed with 'www'
]
CSRF_COOKIE_SECURE = True  # Use this if you're using HTTPS
SESSION_COOKIE_SECURE = True  # Same here
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
import logging
logging.basicConfig(level=logging.DEBUG)
import os
import certifi

os.environ['SSL_CERT_FILE'] = certifi.where()


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
ALLOWED_HOSTS = ['*']
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='promotions.ast@gmail.com'
EMAIL_HOST_PASSWORD='thqf yxba eqkl ydqv'
EMAIL_PORT=587
EMAIL_USE_TLS=True 

ALLOWED_HOSTS = ['*']


# Application definition
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'ckeditor',
    'import_export',
    
]

JAZZMIN_SETTINGS = {
    "site_title": "Site Admin",
    "site_header": "My Project",
    "site_brand": "Admin Penal",
    "welcome_sign": "Welcome to the Admin",
    "copyright": "© 2025 MyCompany",
    "show_ui_builder": True,
    "topmenu_links": [{"name": "Home", "url": "admin:index"}],
    "icons": {"auth.user": "fas fa-user"},
    "changeform_format": "horizontal_tabs",
     "hide_apps": ["recent actions"],  # hide entire "myapp" label from sidebar

    "show_models": [
        "myapp.Bookingcab",      # replace with your actual model name
        "myapp.Cabenquiry",      # replace with actual model name
        "myapp.Carstype",   
    ],
     "user_avatar": "profile_pic",  # field name on CustomUser model
     "site_logo": "images/astlogoss.png",  # Path relative to static/
    "site_icon": "images/astlogoss.png",     # Favicon (optional)
    "login_logo": "images/astlogoss.png",    # Logo on login page
    # "login_logo_dark": "images/astlogoss.png", 
    #  "show_models": ["myapp.Booking", "myapp.Driver"],  
}

JAZZMIN_UI_TWEAKS = {
    # "theme": "darkly",
    # "dark_mode_theme": "darkly",
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'avt.urls'

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'avt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[ os.path.join(BASE_DIR,'static')] 
STATIC_ROOT= os.path.join(BASE_DIR,'assets') 

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


GOOGLE_API_KEY = ('AIzaSyBpvDz913O7Q5yjT44cyeEwW2l8C4ggHdY')


# settings.py
RAZORPAY_KEY_ID = 'rzp_test_iuB1U9gIEu0NVZ'
RAZORPAY_KEY_SECRET = 'byfDZbVNMDJQv5BIjZas9Cy9'
