# Generated by Django 5.0.4 on 2024-10-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default=0, max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('pick_up_location', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=100, null=True)),
                ('pick_up_time', models.CharField(blank=True, max_length=100, null=True)),
                ('way', models.CharField(choices=[('One', 'One'), ('Two', 'Two')], default='One', max_length=100)),
                ('cab', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cabEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=150)),
                ('drop', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pickup', models.CharField(max_length=255)),
                ('trip', models.CharField(max_length=50)),
                ('departure', models.DateField()),
                ('arrival', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Carstype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(upload_to='cartype')),
                ('car_type', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('included_km', models.FloatField()),
                ('toll_tax', models.CharField(default=0, max_length=100)),
                ('extra_Fare', models.FloatField()),
                ('fuel_prc', models.CharField(max_length=100)),
                ('driver_prc', models.CharField(max_length=100)),
                ('night_prc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page2_Heading', models.CharField(max_length=20)),
                ('Page2_paragraph', models.TextField()),
                ('image1', models.ImageField(default='', upload_to='')),
                ('image2', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page3_span', models.CharField(max_length=50)),
                ('Page3_paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PAGE3HEADING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page3_Heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='page4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page4_Heading', models.CharField(max_length=20)),
                ('Page4_paragraph', models.TextField()),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PAGE5_IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PAGE5_PARA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page5_paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PAGE5HEADING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page5_Heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PAGE7HEADING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page7_Heading', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='page7img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page7_Img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='page7info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page7_Para', models.TextField()),
                ('Page7_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(default=0, upload_to='cartype')),
                ('Tempo_name', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('toll_tax', models.CharField(default=0, max_length=100)),
                ('extra_Fare', models.FloatField()),
                ('fuel_prc', models.CharField(max_length=100)),
                ('driver_prc', models.CharField(max_length=100)),
                ('night_prc', models.CharField(max_length=100)),
            ],
        ),
    ]
