# Generated by Django 5.0.4 on 2024-10-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcab',
            name='total_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
