# Generated by Django 5.0.4 on 2024-10-27 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bookcap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bookingcab'),
        ),
    ]
