# Generated by Django 5.0.7 on 2024-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_payment_bookcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcab',
            name='pick_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
