# Generated by Django 5.0.7 on 2024-10-28 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bookingcab_pick_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcab',
            name='Booking_entery_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingcab',
            name='pick_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
