# Generated by Django 5.0.7 on 2024-10-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bookingcab_booking_entery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcab',
            name='Booking_entery_Date',
        ),
    ]
