# Generated by Django 5.1.2 on 2024-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_bookingcab_booking_entery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcab',
            name='advance_payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingcab',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingcab',
            name='departure_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
