# Generated by Django 5.1.2 on 2024-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_bookingcab_advance_payment_bookingcab_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstype',
            name='car_img',
            field=models.ImageField(blank=True, null=True, upload_to='cartype'),
        ),
    ]
