# Generated by Django 5.1.2 on 2024-11-07 19:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_termsandconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Droplocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop', models.CharField(max_length=100)),
                ('drop_loc_info', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(default=True, null=True, upload_to='')),
                ('place_visit', ckeditor.fields.RichTextField()),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pickuplocation')),
            ],
        ),
    ]
