# Generated by Django 5.1.2 on 2024-11-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pickuplocation_droplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcab',
            name='booking_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
