# Generated by Django 5.1.2 on 2024-11-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bookingcab_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcab',
            name='pick_up_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
