# Generated by Django 5.1.2 on 2024-12-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_bookingcab_pick_up_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page4',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
