# Generated by Django 5.1.2 on 2024-12-06 15:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_page4_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='droplocation',
            name='Key_Travel_Details',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
