# Generated by Django 5.1.2 on 2024-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_droplocation_key_travel_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstype',
            name='toll_tax',
            field=models.CharField(default='included', max_length=100),
        ),
    ]
