# Generated by Django 5.1.2 on 2024-12-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_carstype_toll_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstype',
            name='toll_tax',
            field=models.CharField(default='Extra', max_length=100),
        ),
    ]
