# Generated by Django 5.1.2 on 2024-12-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_contactusformdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationFormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
