# Generated by Django 4.2.23 on 2025-06-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
